# Generated by Django 4.2.6 on 2023-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('courier_id', models.IntegerField()),
                ('packages', models.IntegerField()),
                ('adresy', models.IntegerField()),
                ('paczkomat', models.IntegerField()),
                ('stops_end', models.TimeField()),
                ('pickup_end', models.TimeField()),
            ],
        ),
    ]
