# Generated by Django 4.2.6 on 2023-10-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_courierday_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('packages', models.IntegerField()),
                ('facility_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('facility_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courierday',
            name='date',
        ),
        migrations.AlterField(
            model_name='courierday',
            name='packages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier.facilitypackages'),
        ),
    ]
