# Generated by Django 4.2.6 on 2023-10-14 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courier', '0003_facility_facilitypackages_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitypackages',
            old_name='facility_id',
            new_name='facility',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='facility',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier.facility'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
