# Generated by Django 4.2.6 on 2023-10-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierday',
            old_name='user_id',
            new_name='user',
        ),
    ]
