# Generated by Django 4.2.6 on 2023-10-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_rename_user_id_courierday_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierday',
            old_name='adresy',
            new_name='addresses',
        ),
        migrations.RenameField(
            model_name='courierday',
            old_name='paczkomat',
            new_name='machine',
        ),
    ]
