# Generated by Django 4.2.6 on 2023-11-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0008_rename_adresy_courierday_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierday',
            name='addresses',
            field=models.IntegerField(verbose_name='adresy'),
        ),
        migrations.AlterField(
            model_name='courierday',
            name='machine',
            field=models.IntegerField(verbose_name='paczkomat'),
        ),
        migrations.AlterField(
            model_name='courierday',
            name='packages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier.facilitypackages', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='courierday',
            name='pickup_end',
            field=models.TimeField(verbose_name='koniec zbiorów'),
        ),
        migrations.AlterField(
            model_name='courierday',
            name='stops_end',
            field=models.TimeField(verbose_name='konec adresów'),
        ),
    ]
